<a href="https://colab.research.google.com/github/skrixh/enterprise-retail-data-platform/blob/main/python/26MAS1015/ERDP_Data_Profiling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import json
import xml.etree.ElementTree as ET

In [3]:
pos = pd.read_csv("pos_transactions.csv")
pos.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
pos.shape

(10000, 8)

In [5]:
pos.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [6]:
pos.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [7]:
pos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    10000 non-null  object
 1   StockCode    10000 non-null  object
 2   Description  9958 non-null   object
 3   Quantity     10000 non-null  int64
 4   InvoiceDate  10000 non-null  object
 5   UnitPrice    10000 non-null  float64
 6   CustomerID   7709 non-null   float64
 7   Country      10000 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 625.1+ KB

In [8]:
pos.isnull().sum()

InvoiceNo         0
StockCode         0
Description      42
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     2291
Country           0
dtype: int64

In [9]:
missing = pos.isnull().sum()

missing_percentage = (
    pos.isnull().mean() * 100
)

missing_report = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_percentage
})

missing_report

             Missing_Count  Missing_Percentage
InvoiceNo                0                0.00
StockCode                0                0.00
Description             42                0.42
Quantity                 0                0.00
InvoiceDate              0                0.00
UnitPrice                0                0.00
CustomerID            2291               22.91
Country                  0                0.00

In [10]:
pos.duplicated().sum()

np.int64(196)

In [11]:
pos.nunique()

InvoiceNo       512
StockCode      2015
Description    1981
Quantity        114
InvoiceDate     442
UnitPrice       154
CustomerID      323
Country          15
dtype: int64

In [12]:
pos.describe()

           Quantity     UnitPrice    CustomerID
count  10000.000000  10000.000000   7709.000000
mean       7.828600      3.837412  15615.462576
std      104.322417     14.310148   1756.540802
min    -9360.000000      0.000000  12395.000000
25%        1.000000      1.250000  14388.000000
50%        2.000000      2.510000  15605.000000
75%        8.000000      4.210000  17228.000000
max     2880.000000    887.520000  18239.000000

In [13]:
pos["Country"].value_counts()

Country
United Kingdom    9403
Germany            181
EIRE               109
France             106
Norway              73
Lithuania           34
Italy               24
Japan               16
Australia           14
Belgium             12
Poland               8
Portugal             7
Switzerland          6
Spain                5
Netherlands          2
Name: count, dtype: int64

In [15]:
def profile_dataset(df, dataset_name):

    print("=" * 60)
    print(f"DATASET: {dataset_name}")
    print("=" * 60)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nMissing Percentage:")
    print((df.isnull().mean() * 100).round(2))

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nUnique Values:")
    print(df.nunique())

    print("\nNumerical Summary:")
    print(df.describe())

In [16]:
profile_dataset(pos, "POS Transactions")

============================================================
DATASET: POS Transactions
============================================================

Shape:
(10000, 8)

Columns:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Data Types:
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

Missing Values:
InvoiceNo         0
StockCode         0
Description      42
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     2291
Country           0
dtype: int64

Missing Percentage:
InvoiceNo       0.00
StockCode       0.00
Description     0.42
Quantity        0.00
InvoiceDate     0.00
UnitPrice       0.00
CustomerID     22.91
Country         0.00
dtype: float64

Duplicate Rows:
196

Unique Values:
InvoiceNo       512
StockCode      2015
Description    1981
Quantity        114
InvoiceDate     442
UnitPrice       154
CustomerID      323
Country          15
dtype: int64

Numerical Summary:
           Quantity     UnitPrice    CustomerID
count  10000.000000  10000.000000   7709.000000
mean       7.828600      3.837412  15615.462576
std      104.322417     14.310148   1756.540802
min    -9360.000000      0.000000  12395.000000
25%        1.000000      1.250000  14388.000000
50%        2.000000      2.510000  15605.000000
75%        8.000000      4.210000  17228.000000
max     2880.000000    887.520000  18239.000000

###E-commerce

In [18]:
ecommerce = pd.read_excel("/content/ecommerce_orders.xlsx")

In [19]:
profile_dataset(
    ecommerce,
    "E-Commerce Orders"
)

============================================================
DATASET: E-Commerce Orders
============================================================

Shape:
(5000, 7)

Columns:
['order_id', 'customer_id', 'product_id', 'quantity', 'unit_price', 'order_date', 'country']

Data Types:
order_id               object
customer_id           float64
product_id             object
quantity                int64
unit_price            float64
order_date     datetime64[ns]
country                object
dtype: object

Missing Values:
order_id          0
customer_id    1141
product_id        0
quantity          0
unit_price        0
order_date        0
country           0
dtype: int64

Missing Percentage:
order_id        0.00
customer_id    22.82
product_id      0.00
quantity        0.00
unit_price      0.00
order_date      0.00
country         0.00
dtype: float64

Duplicate Rows:
49

Unique Values:
order_id        450
customer_id     310
product_id     1583
quantity         93
unit_price      124
order_date      403
country          15
dtype: int64

Numerical Summary:
        customer_id     quantity   unit_price                     order_date
count   3859.000000  5000.000000  5000.000000                           5000
mean   15625.321586     9.076200     3.582648  2010-12-03 05:09:04.943999744
min    12395.000000  -320.000000     0.000000            2010-12-01 08:26:00
25%    14388.000000     1.000000     1.250000            2010-12-01 16:49:00
50%    15646.000000     2.000000     2.510000            2010-12-02 16:59:00
75%    17228.000000     8.000000     4.210000            2010-12-05 10:25:30
max    18239.000000  1824.000000   295.000000            2010-12-05 16:24:00
std     1748.809697    41.754759     5.931487                            NaN

###CRM

In [20]:
with open("/content/customers.json", "r") as f:
    crm_data = json.load(f)

crm = pd.DataFrame(crm_data)

In [21]:
profile_dataset(crm,"CRM Customers")

============================================================
DATASET: CRM Customers
============================================================

Shape:
(323, 3)

Columns:
['customer_id', 'country', 'source_note']

Data Types:
customer_id    object
country        object
source_note    object
dtype: object

Missing Values:
customer_id    0
country        0
source_note    0
dtype: int64

Missing Percentage:
customer_id    0.0
country        0.0
source_note    0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
customer_id    323
country         15
source_note      1
dtype: int64

Numerical Summary:
       customer_id         country  \
count          323             323
unique         323              15
top        13174.0  United Kingdom
freq             1             297

                                              source_note
count                                                 323
unique                                                  1
top     Derived customer record from UCI Online Retail...
freq                                                  323

###Inventory - XML

In [22]:
tree = ET.parse("/content/inventory.xml")
root = tree.getroot()

Converting into dictionaries

In [23]:
inventory_data = []

for item in root:
    record = {}

    for child in item:
        record[child.tag] = child.text

    inventory_data.append(record)

inventory = pd.DataFrame(inventory_data)

In [24]:
profile_dataset(inventory,"Inventory")

============================================================
DATASET: Inventory
============================================================

Shape:
(2015, 5)

Columns:
['product_id', 'product_description', 'unit_price', 'stock_quantity', 'reorder_level']

Data Types:
product_id             object
product_description    object
unit_price             object
stock_quantity         object
reorder_level          object
dtype: object

Missing Values:
product_id              0
product_description    20
unit_price              0
stock_quantity          0
reorder_level           0
dtype: int64

Missing Percentage:
product_id             0.00
product_description    0.99
unit_price             0.00
stock_quantity         0.00
reorder_level          0.00
dtype: float64

Duplicate Rows:
0

Unique Values:
product_id             2015
product_description    1965
unit_price              132
stock_quantity          484
reorder_level            80
dtype: int64

Numerical Summary:
       product_id     product_description unit_price stock_quantity  \
count        2015                    1995       2015           2015
unique       2015                    1965        132            484
top         21693  TEA TIME PARTY BUNTING       1.25            479
freq            1                       2        206             11

       reorder_level
count           2015
unique            80
top               50
freq              44

###Supplier -  SQL

In [26]:
supplier = pd.read_csv("/content/stg_suppliers_orders.txt")

In [27]:
print(supplier.head())

  purchase_order_id supplier_id product_id  quantity  unit_cost  order_date  \
0          PO000001      SUP056      22819       134       0.32  2026-04-26
1          PO000002      SUP043      22985       109       0.33  2026-04-12
2          PO000003      SUP001      22121       124       4.81  2026-01-22
3          PO000004      SUP029      22912        36       3.95  2026-05-06
4          PO000005      SUP007      22706        41       0.21  2026-04-29

  expected_delivery_date order_status
0             2026-04-30      Pending
1             2026-04-20   In Transit
2             2026-01-29    Delivered
3             2026-05-14   In Transit
4             2026-05-04    Delivered

In [28]:
print(supplier.shape)

(2000, 8)

In [29]:
print(supplier.columns)

Index(['purchase_order_id', 'supplier_id', 'product_id', 'quantity',
       'unit_cost', 'order_date', 'expected_delivery_date', 'order_status'],
      dtype='object')

In [32]:
profile_dataset(supplier, "Supplier Orders")

============================================================
DATASET: Supplier Orders
============================================================

Shape:
(2000, 8)

Columns:
['purchase_order_id', 'supplier_id', 'product_id', 'quantity', 'unit_cost', 'order_date', 'expected_delivery_date', 'order_status']

Data Types:
purchase_order_id          object
supplier_id                object
product_id                 object
quantity                    int64
unit_cost                 float64
order_date                 object
expected_delivery_date     object
order_status               object
dtype: object

Missing Values:
purchase_order_id         0
supplier_id               0
product_id                0
quantity                  0
unit_cost                 0
order_date                0
expected_delivery_date    0
order_status              0
dtype: int64

Missing Percentage:
purchase_order_id         0.0
supplier_id               0.0
product_id                0.0
quantity                  0.0
unit_cost                 0.0
order_date                0.0
expected_delivery_date    0.0
order_status              0.0
dtype: float64

Duplicate Rows:
0

Unique Values:
purchase_order_id         2000
supplier_id                 80
product_id                1271
quantity                   281
unit_cost                  601
order_date                 181
expected_delivery_date     187
order_status                 3
dtype: int64

Numerical Summary:
          quantity    unit_cost
count  2000.000000  2000.000000
mean    159.999000     3.055495
std      80.568453    16.032443
min      20.000000     0.010000
25%      89.000000     0.807500
50%     162.000000     1.540000
75%     226.250000     2.850000
max     300.000000   437.180000

In [33]:
summary = []

datasets = {
    "POS": pos,
    "E-Commerce": ecommerce,
    "CRM": crm,
    "Inventory": inventory,
    "Supplier": supplier
}

for name, df in datasets.items():

    summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing_Values": df.isnull().sum().sum(),
        "Duplicate_Rows": df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

      Dataset   Rows  Columns  Missing_Values  Duplicate_Rows
0         POS  10000        8            2333             196
1  E-Commerce   5000        7            1141              49
2         CRM    323        3               0               0
3   Inventory   2015        5              20               0
4    Supplier   2000        8               0               0